spring:
  redis:
    pool.max-idle: 8
    pool.min-idle: 4
    pool.max-active: 16
    pool.max-wait: -1
  data:
    redis:
      database: 0
      password:
      port: 6379
      host: 10.20.9.85

ae:
  saveType: local